{% set name = "sagetex" %}
{% set version = "3.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/sagemath/sagetex/archive/sagetex-{{ version }}.tar.gz
  sha256: c77e73167fce0f1ff33441148de9538bdcc9b3a87f2a1447e3dd8ab8ca2179de

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  # Can't import sagetex without sage and sagetex is a dependency of sage
  commands:
    - test -f $PREFIX/share/texmf/tex/latex/sagetex/sagetex.sty  # [unix]

about:
  home: http://github.com/sagemath/sagetex
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: Embed code, results of computations, and plots from the Sage mathematics software suite into LaTeX documents

extra:
  recipe-maintainers:
    - conda-forge/sage
