{% set name = "sagetex" %}
{% set version = "3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/sagemath/sagetex/releases/download/v{{ version }}/sagetex-{{ version }}.tar.gz
  sha256: f1ebfacd18fbe99e157efbff3fce3b7ecfa1b8c9824b9b818b458b8a366f4584

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  # Can't import sagetex without sage and sagetex is a dependency of sage
  commands:
    - test -f $PREFIX/share/texmf/tex/latex/sagetex/sagetex.sty  # [unix]

about:
  home: http://github.com/sagemath/sagetex
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: 'Embed code, results of computations, and plots from the Sage mathematics software suite into LaTeX documents'

extra:
  recipe-maintainers:
    - conda-forge/sage
