travis:
  secure:
    BINSTAR_TOKEN: QMtVldL3aMcZxudVJHfI85p8jg53j1faWFPfKR1S8KKS19OEXMnR+4y2rVc2PiWtia/HdRfn/qQMsF5kdUwlmIBzCckJPabLKdJmFkItXQSh8ga/6Wy96saWKqw7kwnqHZ2DjgWyw3W39U0kY+TJIrOdLO6NIecflel5ghJd2hTRtr3LLTHh8vIReZjJDF4hdZpzL74u4nlY0yOVAk/BrJhx12wCcRpv7cePG7fW99kQUlqvEwRPwZwACbSqosaYTiUKcI9GQbocA6Rn5VOAn8Jj53N+qx9HdPgLXW9t+J8BdxmicNZg+PwMWpZjZ4ewa9oHPwAH8nDdf0njMJMvH1bURavLVGdgL5fWaMhOOhDs354c+xO3riIL2CHDSJk/FxfpyrTj3tj9T/DDP1K0QS4AnLnr3SJhBLOxOyV0rSun8JDhj40RnbLNNz0kyqWST4anXCpGjaQdgr0C2MqCPvp6FgAWrTQQN8EsSgJTP0mTyJKYvkRoYWcz0j5dx0Fw61zB8Ppy+p1ywcCOd/uE9Shq7IZeI/AncE7M84noqOjypBfIvV6vzYU35rTwrPK7isrHqiHepuVyZnDzZ+swpDwOj1Q8w0Fs+lb3assqU46NnSZUTwXFVXR5d9h1HDSPCQlnA8o++55fsvF0szQkJ0CKVCqtlHTsxi07tAdB240=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
